import { CompanyReviews } from "../interfaces";

export const companyReviews: CompanyReviews[] = [
  {
    id: "1",
    name: "Tech Solutions",
    location: "Rabat",
    avatarUrl: "https://placehold.co/150",
    description:
      "Tech Solutions is a leading provider of technology solutions, offering innovative products and services to businesses and individuals.",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 120,
    jobsTotal: 80,
  },
  {
    id: "2",
    name: "Vinca Digital",
    location: "Casablanca",
    avatarUrl: "https://placehold.co/150",
    description:
      "Vinca Digital is a digital marketing agency that specializes in creating effective online strategies for businesses.",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 95,
    jobsTotal: 60,
  },
  {
    id: "3",
    name: "Backend Solutions",
    location: "Marrakech",
    avatarUrl: "https://placehold.co/150",
    description:
      "Backend Solutions is a software development company that specializes in creating custom software solutions for businesses.",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 150,
    jobsTotal: 120,
  },
  {
    id: "4",
    name: "Data Insights",
    location: "Tanger",
    avatarUrl: "https://placehold.co/150",
    description:
      "Data Insights is a data analytics company that specializes in providing data-driven insights to businesses.",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 80,
    jobsTotal: 40,
  },
  {
    id: "5",
    name: "Creative Minds",
    location: "Fès",
    avatarUrl: "https://placehold.co/150",
    description:
      "Creative Minds is a creative agency that specializes in creating innovative design solutions for businesses.",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 110,
    jobsTotal: 90,
  },
  {
    id: "6",
    name: "Innovative Solutions",
    location: "Agadir",
    avatarUrl: "https://placehold.co/150",
    description:
      "Innovative Solutions is a technology consulting company that specializes in providing innovative solutions to businesses.",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 75,
    jobsTotal: 50,
  },
  {
    id: "7",
    name: "Future Tech",
    location: "Oujda",
    avatarUrl: "https://placehold.co/150",
    description:
      "Future Tech is a technology consulting company that specializes in providing innovative solutions to businesses.",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 130,
    jobsTotal: 70,
  },
  {
    id: "8",
    name: "NextGen Innovations",
    location: "Tétouan",
    avatarUrl: "https://placehold.co/150",
    description:
      "NextGen Innovations is a technology consulting company that specializes in providing innovative solutions to businesses.",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 90,
    jobsTotal: 30,
  },
];
