import { Company, CompanyDetails } from "../interfaces";

export const companies: Company[] = [
  {
    id: "1",
    name: "Tech Solutions",
    location: "Rabat",
    avatarUrl: "https://placehold.co/150",
    description:
      "Tech Solutions is a leading provider of technology solutions, offering innovative products and services to businesses and individuals.",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 120,
    jobsTotal: 80,
  },
  {
    id: "2",
    name: "Vinca Digital",
    location: "Casablanca",
    avatarUrl: "https://placehold.co/150",
    description:
      "Vinca Digital is a digital marketing agency that specializes in creating effective online strategies for businesses.",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 95,
    jobsTotal: 60,
  },
  {
    id: "3",
    name: "Backend Solutions",
    location: "Marrakech",
    avatarUrl: "https://placehold.co/150",
    description:
      "Backend Solutions is a software development company that specializes in creating custom software solutions for businesses.",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 150,
    jobsTotal: 120,
  },
  {
    id: "4",
    name: "Data Insights",
    location: "Tanger",
    avatarUrl: "https://placehold.co/150",
    description:
      "Data Insights is a data analytics company that specializes in providing data-driven insights to businesses.",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 80,
    jobsTotal: 40,
  },
  {
    id: "5",
    name: "Creative Minds",
    location: "Fès",
    avatarUrl: "https://placehold.co/150",
    description:
      "Creative Minds is a creative agency that specializes in creating innovative design solutions for businesses.",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 110,
    jobsTotal: 90,
  },
  {
    id: "6",
    name: "Innovative Solutions",
    location: "Agadir",
    avatarUrl: "https://placehold.co/150",
    description:
      "Innovative Solutions is a technology consulting company that specializes in providing innovative solutions to businesses.",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 75,
    jobsTotal: 50,
  },
  {
    id: "7",
    name: "Future Tech",
    location: "Oujda",
    avatarUrl: "https://placehold.co/150",
    description:
      "Future Tech is a technology consulting company that specializes in providing innovative solutions to businesses.",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 130,
    jobsTotal: 70,
  },
  {
    id: "8",
    name: "NextGen Innovations",
    location: "Tétouan",
    avatarUrl: "https://placehold.co/150",
    description:
      "NextGen Innovations is a technology consulting company that specializes in providing innovative solutions to businesses.",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 90,
    jobsTotal: 30,
  },
];

/**
 * A diverse list of company details demonstrating different scenarios.
 * Some entries include all optional fields while others omit a few.
 */
export const companyDetails: CompanyDetails[] = [
  {
    id: "1",
    name: "Tech Solutions",
    location: "Rabat",
    avatarUrl: "https://placehold.co/150",
    emloyers: 100,
    dateFounded: "2020-01-01",
    siteUrl: "https://www.techsolutions.com",
    description:
      "Tech Solutions is a leading provider of innovative tech solutions and services, specializing in cutting-edge software development, cloud computing infrastructure, cybersecurity solutions, and digital transformation consulting. With a track record of successful implementations across various industries, we deliver enterprise-grade solutions that help businesses scale and thrive in the digital age. Our team of expert engineers and consultants work tirelessly to ensure our clients receive the highest quality technological solutions tailored to their specific needs.",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 120,
    jobsTotal: 80,
  },
  {
    id: "2",
    name: "Vinca Digital",
    location: "Casablanca",
    // Omitting avatarUrl and salaryRange
    emloyers: 150,
    dateFounded: "2018-05-15",
    siteUrl: "https://www.vincadigital.com",
    description:
      "Vinca Digital specializes in digital marketing strategies and online brand building.",
    industry: "Marketing",
    rating: 4.7,
    reviewsNum: 95,
    jobsTotal: 60,
  },
  {
    id: "3",
    name: "Backend Solutions",
    location: "Marrakech",
    avatarUrl: "https://placehold.co/150",
    // Omitting description and siteUrl
    emloyers: 50,
    dateFounded: "2015-07-20",
    industry: "Renewable Energy",
    rating: 4.2,
    reviewsNum: 80,
    jobsTotal: 45,
  },
  {
    id: "4",
    name: "Data Insights",
    location: "Tanger",
    avatarUrl: "https://placehold.co/150",
    emloyers: 200,
    dateFounded: "2010-03-10",
    siteUrl: "https://www.healthconnect.com",
    description:
      "Health Connect delivers cutting-edge solutions in healthcare connectivity and logistics.",
    industry: "Healthcare",
    salaryRange: "90,000 - 140,000",
    rating: 4.8,
    reviewsNum: 150,
    jobsTotal: 110,
  },
  {
    id: "5",
    name: "Creative Minds",
    location: "Fès",
    // Omitting multiple optional fields (avatarUrl, description, siteUrl, salaryRange, reviewsNum, jobsTotal)
    emloyers: 80,
    dateFounded: "2012-09-25",
    industry: "Finance",
    rating: 4.0,
  },
  {
    id: "7",
    name: "Innovative Solutions",
    location: "Oujda",
    avatarUrl: "https://placehold.co/150",
    emloyers: 120,
    dateFounded: "2019-11-30",
    siteUrl: "https://www.futuretech.com",
    description:
      "Future Tech is at the forefront of emerging technologies, specializing in AI, machine learning, and blockchain solutions. Our innovative approach helps businesses leverage cutting-edge technology to stay ahead of the competition.",
    industry: "Technology",
    salaryRange: "110,000 - 160,000",
    rating: 4.6,
    reviewsNum: 130,
    jobsTotal: 70,
  },
  {
    id: "8",
    name: "Future Tech",
    location: "Tétouan",
    avatarUrl: "https://placehold.co/150",
    emloyers: 75,
    dateFounded: "2021-03-15",
    siteUrl: "https://www.nextgeninnovations.com",
    description:
      "NextGen Innovations focuses on developing next-generation software solutions and digital transformation services. We help businesses modernize their technology stack and improve operational efficiency.",
    industry: "Technology",
    salaryRange: "95,000 - 145,000",
    rating: 4.3,
    reviewsNum: 90,
    jobsTotal: 30,
  },
  {
    id: "9",
    name: "NextGen Innovations",
    location: "Kenitra",
    // Omitting some optional fields to maintain diversity
    emloyers: 60,
    dateFounded: "2022-01-10",
    industry: "Technology",
    rating: 4.1,
    reviewsNum: 45,
    jobsTotal: 25,
  },
];
