import { CompanyReviews } from "../interfaces";

export const companyReviews: CompanyReviews[] = [
  {
    id: "1",
    name: "Tech Solutions",
    location: "Rabat",
    avatarUrl: "https://placehold.co/150",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 100,
    jobsTotal: 100,
  },
  {
    id: "2",
    name: "Vinca Digital",
    location: "Casablanca",
    avatarUrl: "https://placehold.co/150",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 100,
    jobsTotal: 100,
  },
  {
    id: "3",
    name: "Backend Solutions",
    location: "Marrakech",
    avatarUrl: "https://placehold.co/150",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 100,
    jobsTotal: 100,
  },
  {
    id: "4",
    name: "Data Insights",
    location: "Tanger",
    avatarUrl: "https://placehold.co/150",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 100,
    jobsTotal: 100,
  },
  {
    id: "5",
    name: "Data Insights",
    location: "Tanger",
    avatarUrl: "https://placehold.co/150",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 100,
    jobsTotal: 100,
  },
  {
    id: "6",
    name: "Creative Minds",
    location: "Fès",
    avatarUrl: "https://placehold.co/150",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 100,
    jobsTotal: 100,
  },
  {
    id: "7",
    name: "Creative Minds",
    location: "Fès",
    avatarUrl: "https://placehold.co/150",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 100,
    jobsTotal: 100,
  },
  {
    id: "8",
    name: "Creative Minds",
    location: "Fès",
    avatarUrl: "https://placehold.co/150",
    industry: "Technology",
    salaryRange: "100,000 - 150,000",
    rating: 4.5,
    reviewsNum: 100,
    jobsTotal: 100,
  },
];
