import { User } from "../interfaces/user.inteface";

export const MOCK_USER: User = {
  id: "1",
  name: "John Doe",
  email: "john.doe@example.com",
  password: "123456",
  phone: "+33612345678",
  accountType: "Candidat",
  address: "123 Rue de la Paix, 75000 Paris, France",
  birthDate: "1990-01-01",
  gender: "male",
  resumePath: "/cvs/mycv.pdf",
  postulyCVPath: "/cvs/sample.pdf",
  experience: [
    {
      company: "Google",
      position: "Software Engineer",
      startDate: "2020-01-01",
      endDate: "2021-01-01",
    },
  ],
};

export const MOCK_USERS: User[] = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@example.com",
    password: "123456",
    phone: "+33612345678",
    accountType: "Candidat",
    address: "123 Rue de la Paix, 75000 Paris, France",
    birthDate: "1990-01-01",
    gender: "male",
    resumePath: "/cvs/mycv.pdf",
    postulyCVPath: "/cvs/sample.pdf",
    experience: [
      {
        company: "Google",
        position: "Software Engineer",
        startDate: "2020-01-01",
        endDate: "2021-01-01",
      },
    ],
  },
  {
    id: "2",
    name: "Jane Doe",
    email: "jane.doe@example.com",
    password: "123456",
    phone: "+33612345679",
    accountType: "Candidat",
    address: "456 Avenue des Champs-Élysées, 75008 Paris, France",
    birthDate: "1992-02-02",
    gender: "female",
    resumePath: "/cvs/jane_cv.pdf",
    postulyCVPath: "/cvs/jane_sample.pdf",
    experience: [
      {
        company: "Facebook",
        position: "Product Manager",
        startDate: "2019-01-01",
        endDate: "2020-12-31",
      },
    ],
  },
  {
    id: "3",
    name: "Alice Smith",
    email: "alice.smith@example.com",
    password: "123456",
    phone: "+33612345680",
    accountType: "Candidat",
    address: "789 Boulevard Saint-Germain, 75006 Paris, France",
    birthDate: "1988-03-03",
    gender: "female",
    resumePath: "/cvs/alice_cv.pdf",
    postulyCVPath: "/cvs/alice_sample.pdf",
    experience: [
      {
        company: "Amazon",
        position: "Data Scientist",
        startDate: "2021-01-01",
        endDate: "2022-12-31",
      },
    ],
  },
  {
    id: "4",
    name: "Bob Johnson",
    email: "bob.johnson@example.com",
    password: "123456",
    phone: "+33612345681",
    accountType: "Candidat",
    address: "321 Rue de Rivoli, 75001 Paris, France",
    birthDate: "1985-04-04",
    gender: "male",
    resumePath: "/cvs/bob_cv.pdf",
    postulyCVPath: "/cvs/bob_sample.pdf",
    experience: [
      {
        company: "Microsoft",
        position: "DevOps Engineer",
        startDate: "2018-01-01",
        endDate: "2020-12-31",
      },
    ],
  },
  {
    id: "5",
    name: "Charlie Brown",
    email: "charlie.brown@example.com",
    password: "123456",
    phone: "+33612345682",
    accountType: "Candidat",
    address: "654 Rue de la Paix, 75002 Paris, France",
    birthDate: "1995-05-05",
    gender: "male",
    resumePath: "/cvs/charlie_cv.pdf",
    postulyCVPath: "/cvs/charlie_sample.pdf",
    experience: [
      {
        company: "IBM",
        position: "Cloud Architect",
        startDate: "2020-01-01",
        endDate: "2022-12-31",
      },
    ],
  },
];
